---
- name: Setup mac-os-x
  hosts: localhost
  connection: local
  vars_files:
    - group_vars/localhost.yml
  roles:
    - { role: homebrew, tags: [ homebrew ] }
    - { role: vagrant, tags: [ vagrant ] }
    - { role: rbenv, tags: [ rbenv ] }
